### ISSUE TITLE
line 508, in setFrequency

### ISSUE THREAD

**Issue by narezzi** [stef/wireless-radar#2]
Dear Stef,

I m very please with your code, I m trying to run so I could use for my study of the RSSI.

Mrssi is what I m after but I m having this issue

Please let me know if you could help.

Thanks

Traceback (most recent call last):
  File "./wprox.py", line 66, in run
    Wireless(self.interface).setFrequency(self.freq)
  File "/usr/local/lib/python2.7/dist-packages/pythonwifi/iwlibs.py", line 508, in setFrequency
    iwreq)
  File "/usr/local/lib/python2.7/dist-packages/pythonwifi/iwlibs.py", line 1038, in iw_set_ext
    return self.iw_get_ext(ifname, operation, data)
  File "/usr/local/lib/python2.7/dist-packages/pythonwifi/iwlibs.py", line 1033, in iw_get_ext
    result = self._fcntl(request, ifreq)
  File "/usr/local/lib/python2.7/dist-packages/pythonwifi/iwlibs.py", line 1020, in _fcntl
    return fcntl.ioctl(self.sockfd.fileno(), request, args)
IOError: [Errno 22] Invalid argument

**Comment by stef** [comment]
i think the problem is that one of the frequencies is not supported: https://github.com/stef/wireless-radar/blob/master/wirelessradar/mrssi.py#L17 is the chan map, i think it is also replicated in the other py files. play with it and iwconfig to figure out which frequencies are supported by your wifi card. if that helps, would be nice to know which freqs were causing trouble, might be useful for others.

**Comment by narezzi** [comment]
wlan6mon  IEEE 802.11bgn  Mode:Monitor  Frequency:2.427 GHz  Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

**Comment by stef** [comment]
can you try if it works if you only have the entry for 2.427GHz in the mapping?

**Comment by stef** [comment]
do you use wlan0 or mon0 for this? i think you have to put the interface to monitor mode.

**Comment by narezzi** [comment]
can you try if it works if you only have the entry for 2.427GHz in the mapping?
Do you want me to add in to the code? 

do you use wlan0 or mon0 for this? i think you have to put the interface to monitor mode.

yes I m using wlan6mon that is my monitor interface armon-ng is working fine

I have re-download the version from the Python site and seems I did run the 

./wprox.py wlan6mon 

WARNING: No route found for IPv6 destination :: (no default route?)
typ AP SSID\*                      MAC               vendor                  channels              cnt  max  min  avg  sp rssi   flg attempts

And stops

**Comment by stef** [comment]
can you replace the dict in line https://github.com/stef/wireless-radar/blob/master/wirelessradar/wprox.py#L17 til line 29 with the following dict and try again?
    chanmap = {"2427": 4}

**Comment by narezzi** [comment]
Hello Stef,

I've tried this and also I didn't work.... 

Thanks once again for helping me on this

**Comment by stef** [comment]
can you post the output please?

**Comment by narezzi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7521616/16418053/272bfeee-3d40-11e6-85b4-36ddfa7f0b29.png)

**Comment by stef** [comment]
that is very strange. what happens, when you press ctrl-c? can you post that output? seems to hang somewhere it seems.

**Comment by narezzi** [comment]
Stef, 

I just press enter to run and then drop a line nothing happen.

I haven't control c at all.

What version of Linux have you used in order to make it work.

**Comment by stef** [comment]
i doubt this has anything to do with a linux version, i suspect it is a difference in the wireless device. what kind of wireless device do you have? anyway, still interested in where it hangs, pls paste the output of the following steps:
1. ./wprox.py wlan6mon 
2. press control-c to interrupt the program started in 1.
3. copy/paste the output here.

**Comment by narezzi** [comment]
Alsa Network 

wlan6mon  IEEE 802.11bgn  Mode:Monitor  Frequency:2.427 GHz  Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

Teamviewer?

Thanks

**Comment by narezzi** [comment]
Would you say that possible could be the IPV6?

Answer = NO 

Just disabled

**Comment by stef** [comment]
sorry i have no teamviewer. however it would be interesting to know what your wireless card is and what the output is when you interrupt wprox.py.

**Comment by narezzi** [comment]
Stef,

I not sure how could I troubleshooting this as when I run the command I don't received no communication or error the command just drop one line

./wprox.py mon0

Any help ?

**Comment by stef** [comment]
pls execute: https://github.com/stef/wireless-radar/issues/2#issuecomment-229060481

**Comment by narezzi** [comment]
^CTraceback (most recent call last):
  File "./wprox.py", line 10, in <module>
    from scapy.all import sniff, Dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 38, in <module>
    from main import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/main.py", line 8, in <module>

**Comment by stef** [comment]
huh. did you press immediately ctrl-c? this looks very strange, this is the very 1st line. can you wait a bit after starting then press ctrlc and if something else is displayed? if so, can you post it here, if not, can you say, that it's the same output after waiting a couple seconds?

**Comment by narezzi** [comment]
ile "./wprox.py", line 10, in <module>
    from scapy.all import sniff, Dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 16, in <module>
    from arch import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/**init**.py", line 72, in <module>
    from linux import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 73, in <module>
    if _f.close() >> 8 == 0x7f:
KeyboardInterrupt

**Comment by narezzi** [comment]
Stef,

The reason is that the command drops just after I m pressing.

Your stuff really interest me, but I can't make it work.

**Comment by narezzi** [comment]
You may can help in my project,

Could we agree even in a price ...

1)
I need to be able to generate the RSSI from a wlan also the Threseholds Max and Min of that Link 
2)
I need to work in the Bit extract keys from this channel

**Comment by stef** [comment]
it seems i found the problem, python-wifi somehow bitrotted away, and setfrequency instead of frequencies suddenly accepts channel ids, probably the interface below changed, or pythonwifi changed from 0.5 to 0.6? anyway this 2b2b775 should fixe the bug.

**Comment by stef** [comment]
can you confirm that this fixes it please?
